services:
  - type: web
    name: townhall-games
    runtime: node
    repo: https://github.com/adrees/townhall-games
    branch: main
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:relay
    healthCheckPath: /
    envVars:
      - fromGroup: town-hall-games
