services:
  - type: web
    name: townhall-games
    env: node
    region: frankfurt 
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:relay
    healthCheckPath: /
